package command

import (
	"fmt"

	"github.com/codecrafters-io/redis-starter-go/app/internal/keyvaluestore"
	"github.com/codecrafters-io/redis-starter-go/app/internal/respparser"
)

type Command struct {
	CommandType   string
	CommandValues []string
}

type CommandContext struct {
	KeyStore *keyvaluestore.KeyStore
}

type CommandResponse struct {
	Value respparser.RespData
}

var okResponse = respparser.SimpleString{
	Value: "OK",
}

type PingCommand struct{}

type EchoCommand struct {
	Message string
}

type GetCommand struct {
	Key string
}

type SetCommand struct {
	Key                    string
	Value                  string
	RecordExpirationMillis int
}

type TypeCommand struct {
	Key string
}

type AutoGeneratedEntryId int

type XAddCommand struct {
	StreamKey   string
	EntryId     EntryId
	FieldValues map[string]string
}

func (c XAddCommand) GetEntryId() string {
	return fmt.Sprintf("%d-%d", c.EntryId.MillisecondsTime, c.EntryId.SequenceNumber)
}

type XRangeCommand struct {
	StreamKey    string
	StartEntryId EntryId
	EndEntryId   EntryId
}

const (
	NoneAutoGeneratedEntryId AutoGeneratedEntryId = iota
	PartiallyGeneratedEntryId
	FullyGeneratedEntryId
)

// TODO use this struct for other structures
type EntryId struct {
	MillisecondsTime int64
	SequenceNumber   int
	AutoGenerated    AutoGeneratedEntryId
	StreamTopItems   bool // remark: the special '$' arg
}

type XReadStreams struct {
	keysIds map[string]EntryId
}

func ErrorResponse(e error) CommandResponse {
	errContent := respparser.SimpleError{
		Value: e.Error(),
	}
	return CommandResponse{Value: errContent}
}
