package command

import (
	"fmt"

	"github.com/codecrafters-io/redis-starter-go/app/internal/keyvaluestore"
	"github.com/codecrafters-io/redis-starter-go/app/internal/respparser"
)

type Command struct {
	CommandType   string
	CommandValues []string
}

type CommandContext struct {
	KeyStore *keyvaluestore.KeyStore
}

type CommandResponse struct {
	Value respparser.RespData
}

var okResponse = respparser.SimpleString{
	Value: "OK",
}

type PingCommand struct{}

type EchoCommand struct {
	Message string
}

type GetCommand struct {
	Key string
}

type SetCommand struct {
	Key                    string
	Value                  string
	RecordExpirationMillis int
}

type TypeCommand struct {
	Key string
}

type AutoGeneratedEntryId int

const (
	NoneAutoGeneratedEntryId AutoGeneratedEntryId = iota
	PartiallyGeneratedEntryId
	FullyGeneratedEntryId
)

type XAddCommand struct {
	StreamKey               string
	EntryIdMillisecondsTime int64
	EntryIdSequenceNumber   int
	FieldValues             map[string]string
	AutoEntryId             AutoGeneratedEntryId
}

func (c XAddCommand) GetEntryId() string {
	return fmt.Sprintf("%d-%d", c.EntryIdMillisecondsTime, c.EntryIdSequenceNumber)
}

type XRangeCommand struct {
	StreamKey             string
	StartMillisecondsTime int64
	StartSequenceNumber   int
	EndMillisecondsTime   int64
	EndSequenceNumber     int
}

func ErrorResponse(e error) CommandResponse {
	errContent := respparser.SimpleError{
		Value: e.Error(),
	}
	return CommandResponse{Value: errContent}
}
