package command

import (
	"fmt"

	"github.com/codecrafters-io/redis-starter-go/app/internal/keyvaluestore"
	"github.com/codecrafters-io/redis-starter-go/app/internal/respparser"
)

type Command struct {
	CommandType   string
	CommandValues []string
}

type CommandContext struct {
	KeyStore *keyvaluestore.KeyStore
}

type CommandResponse struct {
	Value respparser.RespContent
}

var okResponse = respparser.RespContent{
	Value:    "OK",
	DataType: respparser.SimpleString,
}

type PingCommand struct{}

type EchoCommand struct {
	Message string
}

type GetCommand struct {
	Key string
}

type SetCommand struct {
	Key                    string
	Value                  string
	RecordExpirationMillis int
}

type TypeCommand struct {
	Key string
}

type XaddCommand struct {
	StreamKey                     string
	EntryIdMillisecondsTime       int
	AutogeneratedMillisecondsTime bool
	EntryIdSequenceNumber         int
	AutogeneratedSequenceNumber   bool
	FieldValues                   map[string]string
}

func (c XaddCommand) GetEntryId() string {
	return fmt.Sprintf("%d-%d", c.EntryIdMillisecondsTime, c.EntryIdSequenceNumber)
}

func ErrorResponse(e error) CommandResponse {
	errContent := respparser.RespContent{
		Value:    e.Error(),
		DataType: respparser.SimpleError,
	}
	return CommandResponse{Value: errContent}
}
